project:
  type: book

book:
  title: "Sequential Parameter Optimization Cookbook"
  subtitle: "A guide for scikit-learn and PyTorch"
  author:
  - name: Thomas Bartz-Beielstein
    affiliations:
      - name: SpotSeven Lab
      - city: Gummersbach
        country: Germany
        postal-code: 51643
    orcid: 0000-0002-5938-5158
    email: bartzbeielstein@gmail.com
    url: 'https://www.spotseven.de'
  date: last-modified
  date-format: "MMM D, YYYY"
  sidebar:
    style: docked
    background: light
  search: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2025, T. Bartz-Beielstein" 
    right: 
      - icon: github
        href: https://sequential-parameter-optimization.github.io/Hyperparameter-Tuning-Cookbook/
      - icon: twitter 
        href: https://x.com/bartzbeielstein   
  repo-url: https://github.com/sequential-parameter-optimization/spotpython
  downloads: [pdf]
  sharing: [twitter, linkedin]
  twitter-card: true
  cover-image: cover.png
  cover-image-alt: |
    Sequential Parameter Optimization Toolbox (SPOT) for Python (Logo)
  keyword: "hyperparameter tuning, artificial intelligence, machine learning, streaming data, online algorithms"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



