project:
  type: book
  output-dir: docs

book:
  title: "Sequential Parameter Optimization Cookbook"
  subtitle: "A guide for scikit-learn and PyTorch"
  author:
  - name: Thomas Bartz-Beielstein
    affiliations:
      - name: Bartz & Bartz GmbH and SpotSeven Lab
      - city: Gummersbach
        country: Germany
        postal-code: 51643
    orcid: 0000-0002-5938-5158
    email: bartzbeielstein@gmail.com
    url: 'https://www.spotseven.de'
  date: last-modified
  date-format: "MMM D, YYYY"
  sidebar:
    style: docked
    background: light
  search: true
  page-navigation: true
  page-footer: 
    left: "Copyright 2025, T. Bartz-Beielstein" 
    right: 
      - icon: github
        href: https://sequential-parameter-optimization.github.io/Hyperparameter-Tuning-Cookbook/
      - icon: twitter 
        href: https://x.com/bartzbeielstein   
  repo-url: https://github.com/sequential-parameter-optimization/spotpython
  downloads: [pdf]
  sharing: [twitter, linkedin]
  twitter-card: true
  # cover-image: cover.png
  cover-image-alt: |
    Sequential Parameter Optimization Toolbox (SPOT) for Python (Logo)
  keyword: "optimization, hyperparameter tuning, artificial intelligence, machine learning, streaming data, online algorithms"
  chapters:
    - index.qmd
    - part: "Optimization"
      chapters:
      - 002_awwe.qmd
    - part: "Numerical Methods"
      chapters:
      - 001_surrogate.qmd
      - 001_sampling.qmd
      - 006_constructing_surrogate.qmd
      - 005_num_rsm.qmd
      - 006_num_poly.qmd
      - 006_num_rbf.qmd
      - 006_num_gp.qmd
      - 006_matrices.qmd
      - 006_infill.qmd
    - part: "Sequential Parameter Optimization Toolbox (SPOT)"
      chapters:
      - spotoptim_examples.qmd
      - kriging_surrogate.qmd
      - reproducibility.qmd
      - awwe_optimization.qmd
      - surrogate_selection.qmd
      - pinns_1.qmd
      - pinns_2_hyperparameter_tuning.qmd
      - acquisition_failure.qmd
      - diabetes_dataset.qmd
      - factor_variables.qmd
      - transformations.qmd
      - kriging.qmd
      - learning_rate_mapping.qmd
      - unified_learning_rate.qmd
      - multiobjective.qmd
      - plot_surrogate.qmd
      - point_selection.qmd
      - save_load.qmd
      - success_rate.qmd
      - tensorboard_clean.qmd
      - tensorboard.qmd
      - var_type.qmd
    - references.qmd

bibliography: bart25s.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook
    fontsize: 10pt
    papersize: a4paper
    keep-tex: true
    code-fold: true
    include-in-header:
      text: |
        \usepackage{mdframed}
        \usepackage{pseudo}



